parameters:
    product_images_directory: '%kernel.project_dir%/public/uploads/products'
    uploads_directory: '%kernel.project_dir%/public/uploads'
    # Clés Stripe
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    stripe.client:
        class: Stripe\StripeClient
        arguments:
            - '%env(STRIPE_SECRET_KEY)%'